# Generated by Django 4.1.1 on 2022-10-24 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_ssce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssce',
            name='grade_type',
            field=models.CharField(choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('E8', 'E8'), ('F9', 'F9')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ssce',
            name='subject_type',
            field=models.CharField(choices=[('Eng', 'English'), ('Math', 'Mathematics'), ('che', 'Chemistry'), ('Phy', 'Physics'), ('Bio', 'Biology'), ('civic', 'Civic Education'), ('Gov', 'Government'), ('eco', 'Economics'), ('com', 'Commerce'), ('acc', 'Financial Accounting'), ('Liter', 'Literature_in_English'), ('Agric', 'Agricultural Science')], max_length=50),
        ),
    ]
