# Generated by Django 4.1.1 on 2022-10-23 18:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='passport',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='image/contact'),
            preserve_default=False,
        ),
    ]
